spring:
  application:
    name: vmall-api-gateway
  cloud:
    gateway:
      routes:
        - id: vmall-mall-service
          uri: lb://vmall-mall-service
          predicates:
            - Path=/mall/**
          filters:
            - RewritePath=/mall/(?<segment>.*), /$\{segment}

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
